- backend/main.py
- database/README.md
- database/db_manager.py
secrets 통합에 따른 경로 재설정 및 오타 수정
* 2023/01/25
secrets.yaml으로 DB 정보 통합에 따라 database/db_manager.py도 해당 경로를 따르도록 수정
backend/main.py의 SLACK 정보를 받는 부분의 오타 수정
> Fix: change secrets path & fix typo

- backend/main.py
- backend/service/item.py
- backend/service/user.py
- frontend/src/App.svelte
- frontend/src/Detail.svelte
- frontend/src/Header.svelte
- frontend/src/Login.svelte
- frontend/src/SignUp.svelte
POST로 주고받기
* 2023/01/25
- GET으로 주고받던 것을 POST로 변경하였습니다.
-> login, signup
> Feat : add code with POST

- backend/inference/predict.py
- backend/main.py
버그를 일으키는 변수명 수정 및 model loading 부분 수정
* 2023/01/25
1. model loading이 CPU Only device에서 지원되지 않는 문제를 수정하였습니다
2. backend/main.py 파일에서, secrets 라이브러리와 secrets 변수명이 충돌하는 이슈를 해결하였습니다. 기존 secrets로 의도되었던 변수명에 오타가 있었고 이로 인하여 문제가 없었으나, 오타를 수정함과 동시에 secrets 라이브러리와 충돌이 일어나는 문제가 발생하여 변수명을 수정하였습니다.
2번에 관한 내용은 #31 에서 확인할 수 있습니다.
> Fix: change variable name & set map_location to model loading

- backend/main.py
- frontend/src/Detail.svelte
- frontend/src/Mypage.svelte
마이페이지 구현
* 2023/01/26
좋아요 누른 상품 보는 페이지를 만들었습니다.
- 아직 디테일 부분에서 좋아요 기능에 오류가 있습니다.
> Feat : add mypage

- frontend/src/Login.svelte
* 2023/01/26
- signup url이 반영되지 않은 부분을 수정했습니다.
> Feat: fix signup url

- frontend/src/Mypage.svelte
- frontend/src/SignUp.svelte
* 2023/01/26
- signup 페이지에서 post_member가 작동하지 않는 문제를 해결했습니다.
- mypage에서 url을 .env를 사용하도록 수정했습니다.
> HOTFIX: fix bug

- frontend/src/Detail.svelte
- frontend/src/Home.svelte
- frontend/src/HomeElement/Like.svelte
- frontend/src/Login.svelte
- frontend/src/Mypage.svelte
- frontend/src/SignUp.svelte
* 2023/01/26
- 기타 수정 사항을 수정했습니다.
> Feat: fix url, etc bug

- backend/poetry.lock
- backend/pyproject.toml
poetry 파일 수정
* 2023/01/26
poetry 파일에 "requests" 모듈이 없어서 추가하였습니다.
> Docs : change poetry file

- backend/main.py
- database/sql/create_table.sql
- database/sql/delete_table.sql
backend/main.py에 개발/배포 환경에 따른 가이드 주석 추가 및 sql 구문 추가
* 2023/01/27
1. backend/main.py에서 개발/배포 환경에 따른 가이드 주석을 추가하였습니다
2.  inference_result DB Table에 대응되는 sql 구문을 추가하였습니다
> Docs: add comments for develop

- backend/main.py
- backend/service/item.py
- frontend/src/Home.svelte
회원가입 때 카드 이미지 중복 체크
* 2023/01/29
회원가입때 중복된 집이 나오는 경우가 있어 체크하였습니다.
한 개의 집이 같은 이미지인데도 불구하고 다른 집으로 인식하는 문제가 있는 것 같습니다.
> Feat : without duplicated card image in Signup

- backend/service/item.py
sql query의 데이터타입 확인
* 2023/01/20
sql query에 적용되는 데이터의 타입을 확인하였습니다.
> Feat: check data type at sql query

- backend/db/models.py
- database/sql/create_table.sql
- database/sql/delete_table.sql
cluster_item 테이블 새로 추가
* 2023/01/30
새롭게 사용될 cluster_item 테이블 추가를 위한 코드를 작성했습니다.
> Feat: add cluster_item table at db

- backend/db/models.py
- database/sql/create_table.sql
- database/sql/delete_table.sql
DB에 card Table을 추가하도록 코드 작성
* 2023/01/31
1. house Table에서 card_space, card_img_url 컬럼 삭제
2. card Table 추가
card 테이블에 추가된 컬럼들의 자료형, null 여부, 이름 등이 원하는 명세에 맞게 반영이 되었는지 확인 바랍니다.
추가적으로, 노션에 반영된 ERD도 확인 바랍니다.
> Feat: add card Table at DB

- crawling/preprocess.py
- crawling/preprocess_utils/args.py
- crawling/preprocess_utils/cluster_item.py
- crawling/preprocess_utils/item.py
- crawling/preprocess_utils/utils_category.py
- crawling/preprocess_utils/utils_cluster.py
- crawling/preprocess_utils/utils_similarity.py
- crawling/requirements.txt
Crawling code 이후에 end-to-end로 전처리된 결과 얻을 수 있도록 했습니다.
* 2023/01/31
1. Crawling code 이후에 end-to-end로 전처리된 결과를 얻을 수 있도록 수정했습니다.
2. 전체 데이터셋을 전처리하면 약 40분 넘게 소요되기 때문에 빠른 테스트를 진행하기 위해 아래의 테스트 명령어를 실행해주세요.
`python preprocess.py --run_test 1 --data_path [데이터 경로]`
1. tensorflow, keras의 tokenizer를 위해, tensorflow, keras를 설치해야하니 requirements.txt 를 별도로 설치해주세요.
2. 마찬가지로 konlpy도 설치해야합니다.
3. 폴더 경로 이슈가 있으면 피드백 부탁합니다.
4. 테스트를 진행하려면 python preprocess.py --run_test 1 --data_path [데이터 경로] 를 입력하세요.
> Crawling code 이후에 end-to-end로 전처리된 결과 얻을 수 있도록 했습니다.

- .gitignore
- Dockerfile
- backend/settings.sh
Docker Image 빌드를 위한 Dockerfile을 작성
* 2023/01/31
나만의집 프로젝트 Docker Image 빌드를 위한 Dockerfile을 작성하였습니다
자세한 사항은 노션에 기록되어 있습니다. 
[노션에서 확인하기](https://dear-queen-578.notion.site/Docker-Image-bc74f8af75a8489e9a9ad1725d69a5d8)
> Feat: add Dockerfile

- backend/main.py
- backend/service/item.py
- frontend/src/Detail.svelte
- frontend/src/Home.svelte
- frontend/src/Mypage.svelte
- frontend/src/RecommendItem.svelte
detail 페이지에 관련 상품 추가
* 2023/02/01
- 디테일 페이지 내에 같은 클러스터 상품, 같은 시리즈 상품, 같은 카테고리 인기 상품을 보여주는 것을 추가했습니다.
- 마이페이지에서 상품이 없는 경우를 추가했습니다.
> Feat: add recommend in detail page

- backend/main.py
첫 로그인할 때, 좋아요를 안 누르면 추천이 활성화되지 않도록 API 수정 
* 2023/02/01
1. backend/main.py API 수정: 첫 로그인할 때, 좋아요를 안 누르면 추천이 활성화되지 않도록 API 수정 
1. 없습니다.
> HOTFIX: Fix recommendation problem

- backend/db/models.py
> Hotfix: fix models.py

- backend/db/models.py
- database/sql/create_table.sql
preprocessed_title 컬럼 추가
* 2023/02/02
preprocessed_title 컬럼 추가
> Feat: add preprocessed_title column

- crawling/preprocess.py
- crawling/preprocess_utils/cluster_item.py
- crawling/preprocess_utils/item.py
- crawling/preprocess_utils/utils_similarity.py
preprocess 코드 오류 수정 및 일종의 refactor
* 2023/02/03
1. 전처리 중에 발생하는 에러 해결
2. test 코드 진행 시 원본 데이터가 덮어씌워지는 버그 해결
3. 코드 refactoring
없습니다.
> preprocess 코드 오류 수정 및 일종의 refactor

- gcp/README.md
GCP README.md에서 typo가 존재해서 수정
* 2023/02/03
1. GCP README.md에서 typo가 존재해서 수정
없습니다.
> GCP README.md에서 typo가 존재해서 수정

- gcp/gcp_args.py
GCP region을 바꿨습니다.
* 2023/02/03
GCP region을 바꿨습니다.
없습니다.
> Fix: Change gcp region

- backend/db/models.py
- backend/main.py
- backend/service/user.py
Member table 수정
* 2023/02/03
AB test를 위해 member table에서 회원가입 때 사용자를 count 해주는 coulmn을 만들었습니다.
> Feat : ABtest

- frontend/src/Home.svelte
- frontend/src/HomeElement/Like.svelte
- frontend/src/Loading.svelte
- frontend/src/SignUp.svelte
좋아요 버튼 버그 수정
* 2023/02/03
- 좋아요 버튼이 눌린 채로 상품이 새로고침 되던 문제 해결
#76 메인 페이지 이슈
> Fix: fix like button clicked

- backend/main.py
- frontend/src/Loading.svelte
- frontend/src/SignUp.svelte
> Feat : Loading

- backend/inference/model.yaml
- backend/inference/predict.py
- backend/main.py
- backend/service/item.py
- backend/service/user.py
ABtest 버전 1
* 2023/02/03
ABtest 버전 1입니다.
> Feat : abtest_v1

- frontend/src/Home.svelte
메인 페이지에 마이페이지 설명 문구 추가
* 2023/02/03
- 메인 페이지에서 좋아요를 누른 상품이 마이페이지에 추가된다는 설명 문구 추가
> Fix: main page description

- backend/service/user.py
out of list 이슈
* 2023/02/03
- out of list 문제를 garbage collector의 이슈로 생각하고 문제를 해결했지만 회원가입시 backend 오류가 발생한다면 말씀해주시길 바랍니다.
> Fix : out of list

- backend/service/item.py
비회원 시 필터링 기준 조정
* 2023/02/03
비회원 필터링 기준 변경
rating>='4.7' and price!='' and review>='5' -> rating>='4.0' and price!='' and review>='1'
> Fix : filtering range

- backend/inference/predict.py
- backend/main.py
Inference code를 수정했습니다.
* 2023/02/24
Inference code를 수정했습니다.
1. data/item.tsv 파일을 추가해야 합니다.
> Fix: Fix inference code

- frontend/src/Detail.svelte
- frontend/src/Home.svelte
* 2023/02/04
모바일에서도 상품이 깔끔하게 보이도록 변경하였습니다.
-
> Feat : for mobile

- README.md
프로젝트 README 초안입니다.
* 2023/02/07
프로젝트 README 초안입니다.
검토 후 의견 제시 바랍니다.
우측 상단의 'Display the rich diff' 버튼을 누르시면 직관적으로 파악할 수 있습니다.
> Docs: update README.md draft

- EDA/cluster_evaluate.ipynb
- EDA/cluster_evaluate.py
클러스터링을 DL과 ML을 활용해서 검증했습니다.
* 2023/02/15
1. 클러스터링 검증을 위해 autoencoder로 차원 축소를 진행했습니다.
2. 100차원의 feature로 random forest 알고리즘을 활용해서 검증했습니다.
1. [클러스터링 검증하기](https://github.com/boostcampaitech4lv23recsys2/final-project-level3-recsys-12/wiki/%EB%8D%B0%EC%9D%B4%ED%84%B0#%EC%83%81%ED%92%88%EB%AA%85-%ED%81%B4%EB%9F%AC%EC%8A%A4%ED%84%B0%EB%A7%81-%EA%B2%80%EC%A6%9D%ED%95%98%EA%B8%B0) 위키에 자세한 방법을 상세히 작성했습니다.
> 클러스터링을 DL과 ML을 활용해서 검증했습니다.
